apiVersion: v1
kind: Service
metadata:
  labels:
    app: istio-ingressgateway
    istio: ingressgateway
  name: istio-ingressgateway
  namespace: ingress-gateway
spec:
  ports:
  - name: status-port
    nodePort: 30357
    port: 15021
    protocol: TCP
    targetPort: 15021
  - name: http2
    nodePort: 30946
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    nodePort: 30701
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
  sessionAffinity: None
  type: NodePort
